### ISSUE TITLE
graphics example : image effects don't work in html5 

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#10]
alpha multiplier and tinting effects don't work

**Comment by TerryCavanagh** [comment]
Bollox :/ Will look into this!

**Comment by TerryCavanagh** [comment]
Ok, it looks like OpenFL currently has a different implementation for drawing images in HTML5 that doesn't support alpha. So I guess I'll wait for them to support it in future (which might happen! Just the other day they had an update that got drawcircle to work!)

**Comment by TerryCavanagh** [comment]
Oh, these work now, cool!
