### ISSUE TITLE
Reminder about OpenFL install?

### ISSUE THREAD

**Issue by oscarcs** [TerryCavanagh/haxegon#105]
There's link to the relevant [web page](http://www.openfl.org/learn/docs/getting-started/) ([on the web site](http://haxegon.com/setup.html)) but maybe there should be a link in the README on the project page as well?
I fiddled around for a bit before I remembered to run `haxelib run openfl setup`.
It's a little thing, but there's a good chance beginners will forget this.

**Comment by TerryCavanagh** [comment]
Good call! I've added placeholder openfl setup instructions to the website. I'll update the live site with the next library update, which should hopefully be today:

https://github.com/TerryCavanagh/haxegon.com/commit/a78924b1ff265a74e0ae6e58d40cd8a697706d9c
