### ISSUE TITLE
Starling error on compiling HTML5

### ISSUE THREAD

**Issue by oscarcs** [TerryCavanagh/haxegon#106]
Upon compiling to the html5 target, I get the following:

``` bash
$ openfl test html5
/usr/lib/haxe/lib/haxegon/0,3,2-alpha/starling/core/RenderSupport.hx:86: lines 86-87 : openfl.Vector<Int> should be openfl.Vector<Float>
/usr/lib/haxe/lib/haxegon/0,3,2-alpha/starling/core/RenderSupport.hx:86: lines 86-87 : Type parameters are invariant
/usr/lib/haxe/lib/haxegon/0,3,2-alpha/starling/core/RenderSupport.hx:86: lines 86-87 : Int should be Float
```

This particular error message can be resolved by editing the relevant line the file so that one of the values in the initialized vector is a Float (like 0.0). I then get another error:
``` bash
/usr/lib/haxe/lib/haxegon/0,3,2-alpha/starling/events/EventDispatcher.hx:190: characters 13-47 : openfl.Vector<starling.display.DisplayObject> should be openfl.Vector<starling.events.EventDispatcher>
/usr/lib/haxe/lib/haxegon/0,3,2-alpha/starling/events/EventDispatcher.hx:190: characters 13-47 : Type parameters are invariant
/usr/lib/haxe/lib/haxegon/0,3,2-alpha/starling/events/EventDispatcher.hx:190: characters 13-47 : starling.display.DisplayObject should be starling.events.EventDispatcher
```
Error appears to be in relation to Starling.
OpenFL samples compile and run on my machine, so that all appears to be installed correctly.

Platform is 64-bit Linux (Ubuntu 16.04).

**Comment by oscarcs** [comment]
Ah ha! I found https://github.com/openfl/starling/issues/33
Closing.

**Comment by TerryCavanagh** [comment]
Heh, thanks for trying it out!

Haxegon is still an early alpha, and sadly right now I can only vouch for the flash target (although when the library is finished, the flash target will be a legacy thing and html5 and native will be the lead targets!)

As you've already discovered, I'm waiting for a library update before the html5 target will properly work. Hopefully not much longer!

**Comment by TerryCavanagh** [comment]
Try it now! :)
