### ISSUE TITLE
When I launch example games, the view zooms away to a dot very quickly

### ISSUE THREAD

**Issue by bfod** [TerryCavanagh/haxegon#111]
More visible in the Pong game which puts the text up immediately - it seems to halve in size every frame until it's invisible.

This is on a Mac laptop that is running a hidpi screen with pixel-doubling, maybe that's the issue?

**Comment by TerryCavanagh** [comment]
Hah! Sorry, yeah, this is currently happening on native builds - I think it's a bug with Starling's viewport. I'm stuck with HTML5 and flash until they sort it out, sorry!

**Comment by TerryCavanagh** [comment]
Ok, well, I've gone and reported this one to the Haxe Starling project, so hopefully it'll be sorted out soon!

https://github.com/openfl/starling/issues/35

**Comment by TerryCavanagh** [comment]
That was quick! @jgranick to the rescue again!

I'll make sure the next haxelib version of this has native support, (which means I can finally drop the -alpha bit from the version number...)
