### ISSUE TITLE
Add deltaangle function

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#132]
I.e. the least angle between two angles, signed so that you can add the result to angle 1 to get to the next angle.

**Comment by increpare** [comment]
is deltaangle a good name? "angledifference" might be more understandable!

**Comment by increpare** [comment]
or anglebetween? DUNNO

**Comment by TerryCavanagh** [comment]
Personally, I'm not that bothered what it's called! `anglebetween` sounds good to me! (`deltaangle` is what unity uses, but maybe it's a little techy)
