### ISSUE TITLE
Gfx.scale() pivot does not default to Gfx.CENTER like it should

### ISSUE THREAD

**Issue by bfod** [TerryCavanagh/haxegon#142]
Seems to default to Gfx.LEFT

**Comment by TerryCavanagh** [comment]
Ah, yeah, I changed the default to top left hand corner a while back (in practice it was mostly what I wanted to do). I should fix the documentation, thanks

**Comment by TerryCavanagh** [comment]
Fixed in local branch, will be live with the 0.12.0 update
