### ISSUE TITLE
Fix up Scene.hx

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#153]
Scene.hx needs a structural re-evaluation before 1.0

(related https://github.com/TerryCavanagh/haxegon/issues/143)

Specifically:
 - [ ] Try out a Scene.previous() function
 - [ ] Go through the class and remove old stuff, functions and variables that aren't being used

**Comment by TerryCavanagh** [comment]
Particular problem to figure out: if we want a scene to go back to the previous scene (e.g. a menu going back to a particular game mode), how would we best structure this?

**Comment by increpare** [comment]
can't you just manually keep track of a "last scene" variable if you want
to keep track of where you were?

or maybe you could do this automatically as a static variable or a
"loadpreviousscene" method if you think it'd be of use?

(I assume you don't want to restore state from the scenes or anything, just
reload them from scratch)

i feel like this is something that it's pretty easy to code by hand, and
doesn't come up so often? could you give a more concrete example?

**Comment by TerryCavanagh** [comment]
Basically this is just weird to do with the current structure. It looks something like this:


``` haxe
class Globalstuff{
  public static var oldscene:Dynamic;
}
```

``` haxe
class Scene1{
  public function changescene(){
    Globalstuff.oldscene = this;
    Scene.change(Scene2);
  }
}
```

``` haxe
class Scene2{
  public function changescene(){
    Scene.change(Globalstuff.oldscene);
  }
}
```

...which is... fine? Probably? But definitely seems like it could be expressed in an easier way.

The point of these issues marked "structural" is to figure out the best way to do them ahead of 1.0, once and for all. After that, I probably don't want to change the structure of the library much for a long time, so I wanna get it right.

**Comment by TerryCavanagh** [comment]
(tbh I'm mostly pretty happy with the Scene.hx stuff, and might not change it much. This issue is basically just a to-do, to remind myself to re-evaluate it before 1.0 finalises it)

**Comment by increpare** [comment]
can you mention particular ways this might come up in games, though? have
you made a game that would benefit from this structure? I don't think I
have, fwiw.  Normally, different game modes won't be given different scene
types, and scene flow is normally something that you don't need to know
extra things about.

Are you imagining this being relevant for things like an escape options
menu?

>But definitely seems like it could be expressed in an easier way.

Scene.back()
or
Scene.change(Scene.prevScene)
?

**Comment by TerryCavanagh** [comment]
This comes up in State Machine a fair bit - we're working around it in a slightly awkward feeling way right now. But not sure it's actually worth changing anything over. Just looking through the class now, maybe it's not as messy as I thought it was.

`Scene.back()` should be pretty easy to implement, so I might try it at some point after this 0.9 update is out and see how it feels.
