### ISSUE TITLE
AssetType issue [0.8.0]

### ISSUE THREAD

**Issue by oscarcs** [TerryCavanagh/haxegon#155]
After downloading and attempting to build using 0.8.0, I get the following error:
```
/usr/lib/haxe/lib/haxegon/0,8,0/haxegon/Gfx.hx:1222: characters 25-34 : Type not found : AssetType
```
This can be easily fixed by inserting the following line into Gfx.hx:
``` haxe
import openfl.utils.AssetType;
```

This is fixed in `master`, but maybe it's worth releasing a hotfix for this? Depending on plans for 0.9.0 obviously.

**Comment by TerryCavanagh** [comment]
Ack, right - this'll be because of a recent openfl change. Thanks for the bug report! I'll do a 0.90 release this weekend with what I've got implemented so far!

**Comment by TerryCavanagh** [comment]
0.9.0 released! This should be fixed. Thanks for reporting it!

https://github.com/TerryCavanagh/haxegon/releases/tag/0.9.0
