### ISSUE TITLE
Random.hx redesign

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#180]
Some stuff in this class is a bit flaky. Improve the pseudorandom generator, try some useful test cases, and look at cool libraries like chance.js for inspiration: http://chancejs.com/#weighted

**Comment by TerryCavanagh** [comment]
Considering:
`Random.normal(mean, deviation)`
`Random.weighted(["a", "b", "c"], [10, 20, 30])`

**Comment by increpare** [comment]
normal distribution is a bit high-faluting for haxegon?

2018-01-23 19:34 GMT+01:00 Terry Cavanagh <notifications@github.com>:

**Comment by TerryCavanagh** [comment]
...yeah, you're right. I'll just add the weighted random thing and leave it at that. That's one I've actually used for a game. I've never used a normal distribution.

**Comment by TerryCavanagh** [comment]
Might use this little snippet for an example somewhere:

```haxe
var randomresult:Array<String> = [];
var headsodds:Int = 90;
var tailsodds:Int = 10;
for (i in 0 ... 10000){
  randomresult.push(Random.weighted(["heads", "tails"], [headsodds, tailsodds]));
}
	
var heads:Int = 0;
var tails:Int = 0;
for (i in 0 ... 10000){
  if (randomresult[i] == "heads") heads++;
  if (randomresult[i] == "tails") tails++;
}
		
trace("Tossing a coin 10,000 times:");
trace("Odds set to " + headsodds + "/" + tailsodds);
trace("Heads: " + heads);
trace("Tails: " + tails);
```
