### ISSUE TITLE
how to make things not blurry?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#186]
If I set the resolution to be low in the project.xml of the first sample, it's super blurry in safari and chrome at least

<img width="487" alt="bildschirmfoto 2018-01-09 um 19 45 40" src="https://user-images.githubusercontent.com/465632/34737205-c603ff82-f575-11e7-8451-21d20508a3d2.png">

Is there a way to enable nearest neighbour?

**Comment by increpare** [comment]
setting 

```
<set name="windowwidth" value="0" />
<set name="windowheight" value="0" />
```

and putting the proper definitions in haxedef
```
<haxedef name="windowwidth" value="240" />
<haxedef name="windowheight" value="150" />
```

fixed everything for me

**Comment by TerryCavanagh** [comment]
Ah, that's interesting - will see what I can do about cleaning this all up in the next update.

**Comment by increpare** [comment]
(this gives the same results as just deleting the set name bits outright, fwiw!)

**Comment by increpare** [comment]
(it's still a liiitttle blurry though now that i look more closely...)

**Comment by TerryCavanagh** [comment]
Have deprecated the old project.xml variables, but will need to look into this one properly! https://github.com/TerryCavanagh/haxegon/commit/50300c257bbdf7f5cef49ed7d2fc1fd4308d7650

**Comment by increpare** [comment]
setting
      allow-high-dpi="true"  in  <window seems to fix this

```
	<window
      width="${windowwidth}" height="${windowheight}" unless="mobile" 
      allow-high-dpi="true" 
   ></window>
```

**Comment by TerryCavanagh** [comment]
Thanks a million!
