### ISSUE TITLE
Force static classes for scenes

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#195]
It doesn't actually make any sense to have non static classes for scenes, and leads to confusion and problems if you don't enforce it.

Have haxegon read an init() function instead of a new() function, and throw an error if you haven't included the static keyword

-cons: It adds a little complexity to the Hello World example, but maybe that's not that important

**Comment by TerryCavanagh** [comment]
Uff, naw, shouldn't do this. It actually massively complicates people's first interaction with the library to require every variable in your first class to be static.

What I could do, though, is rename the "new()" function to something else, which deals with the confusion issue. Gonna change it to init().

**Comment by increpare** [comment]
"It doesn't actually make any sense to have non static classes for scenes,
and leads to confusion and problems if you don't enforce it."
why does it make sense for scenes to be static?

being able to easily reset all the variables can be handy - normally if i
load a game it's a new game - isn't preventing accidental leaking of
variables between instances of a scene a good thing? (it's a minor point, I
know)

2018-01-13 19:28 GMT+01:00 Terry Cavanagh <notifications@github.com>:

**Comment by TerryCavanagh** [comment]
Actually, I basically want to implement that exact functionality (https://github.com/TerryCavanagh/haxegon/issues/143), but currently can't because of how haxegon is organised! This is me moving towards that!
