### ISSUE TITLE
way to go from character to keycode?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#203]
there's a helper for the other direction, but this could also be helpful sometimes?

**Comment by TerryCavanagh** [comment]
Sure, I’ll do that!

**Comment by increpare** [comment]
it's missing the numbers + dealing with case, but here's a start for copying/pasting : P 

```
var alphamap = [
      "a"=>Key.A,
      "b"=>Key.B,
      "c"=>Key.C,
      "d"=>Key.D,
      "e"=>Key.E,
      "f"=>Key.F,
      "g"=>Key.G,
      "h"=>Key.H,
      "i"=>Key.I,
      "j"=>Key.J,
      "k"=>Key.K,
      "l"=>Key.L,
      "m"=>Key.M,
      "n"=>Key.N,
      "o"=>Key.O,
      "p"=>Key.P,
      "q"=>Key.Q,
      "r"=>Key.R,
      "s"=>Key.S,
      "t"=>Key.T,
      "u"=>Key.U,
      "v"=>Key.V,
      "w"=>Key.W,
      "x"=>Key.X,
      "y"=>Key.Y,
      "z"=>Key.Z
    ];
```

**Comment by TerryCavanagh** [comment]
Ok, I've done it :D It's not the nicest implementation, but should do for what most people would want to use this function for. A proper implementation would need to take keycode mapping and native correction and so on into account and ahhh I guess I'll do it if anyone actually needs it
