### ISSUE TITLE
Expose Input.keybuffer

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#210]
There are good reasons for giving control of this to the end user!

**Comment by increpare** [comment]
Such's?

2018-01-19 17:58 GMT+01:00 Terry Cavanagh <notifications@github.com>:

**Comment by TerryCavanagh** [comment]
It's not currently possible to grab the text from an `Text.input()` statement *until* you've pressed enter. Which is fine most of the time, probably. But it makes it impossible to, say, make your own fancy text input system for a hacking game, or write your own GUI system with text input.
