### ISSUE TITLE
html5 examples not working?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#22]
lots of the examples aren't working in html (safari 8.0.6)

for instance, the Drawing Shapes only displays one frame, doesn't animate in html5 in safari or chrome or firefox now (works fine in flash and neko). 

for some reasons, some of the games on my website have also broken, even though I haven't changed them (the hair game in your examples packet still works in html). So something's happened to break even older builds even though I haven't done anything? Spooky...

don't see any console error messages

**Comment by increpare** [comment]
http://ded.increpare.com/~locus/blackness_and_stars/
http://ded.increpare.com/~locus/cookiegame/
don't work for me (They worked fine when i uploaded them originally ...)
http://ded.increpare.com/~locus/hairgame/ 
still works

**Comment by increpare** [comment]
I should say, I can see the loading bar, but once it's full, bam, nothing.

**Comment by TerryCavanagh** [comment]
Added to HTML5 milestone. Won't get fixed any time in the next few weeks, but committing to doing some serious work to the HTML5 target down the line.

**Comment by increpare** [comment]
you might wanna double check, but because of #23 this is probably fine now

**Comment by TerryCavanagh** [comment]
Gonna leave this one open for a bit until the HTML5 target has caught up fully!

**Comment by TerryCavanagh** [comment]
HTML5 target is significantly improved now, closing this particular issue!
