### ISSUE TITLE
Regular fonts are currently broken in Terrylib

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#26]
Bitmap fonts work now, but the old TTF fonts aren't working right now.

**Comment by increpare** [comment]
Do we need 'em?

**Comment by increpare** [comment]
need/want

**Comment by increpare** [comment]
oh wait, right this is terrylib, not the online branch. don't mind me - regular fonts are good in vanilla terrylib :)

**Comment by TerryCavanagh** [comment]
This is working again
