### ISSUE TITLE
The black background thing when making haxegon projects

### ISSUE THREAD

**Issue by marioboi3112** [TerryCavanagh/haxegon#333]
so i was trying to make a game using haxegon, but i made it so that the background is cleared Red but there is black rectangle thing on the left and right sides of the game 
![image](https://github.com/haxegon/haxegon/assets/98112470/ce5bcbd5-d5f8-4f6b-8993-598daef83e69)
Any idea why that is?

**Comment by TerryCavanagh** [comment]
Yep! Haxegon has an internal canvas for the screen, and the default behaviour is to scale it up letterboxed to fill the window you're in. If you don't want this behaviour, call this in your main init function:

```haxe
Gfx.resizescreen(0, 0);
```

There's some more information here: https://haxegon.com/reference/gfx.html
