### ISSUE TITLE
Core.time not working (edit: on Neko target)

### ISSUE THREAD

**Issue by marioboi3112** [TerryCavanagh/haxegon#334]
whenever i try to print the elapsed time using Core.time, not sure if its because of the API or my code, just in case, i will drop in my code here, Thanks!
```haxe
package;

import haxegon.*;

class Menu {
	var gameState:String = "menu";
	var start:Float;
	start = Core.time;	
	public function new() {}
	
	public function update() {
		var elapsed:Float = Core.time - start;
		var minutes:Int = Std.int(elapsed / 60);
		var seconds:Int = Std.int(elapsed % 60);
		trace('Time: $minutes:$seconds');
	}
	
	public function menuStateHandler() {
		if (gameState == "menu") {
			Gfx.clearcolor = Col.BLACK;
			Text.display(Text.CENTER, Text.CENTER, "MENU");
		}
	}
}
```
The error is: 
```
Called from openfl/display/DisplayObject.hx line 1400              
Called from a C function                                           
Called from openfl/events/EventDispatcher.hx line 448              
Called from starling/core/Starling.hx line 682                     
Called from starling/core/Starling.hx line 455                     
Called from starling/core/Starling.hx line 469                     
Called from starling/display/Stage.hx line 108                     
Called from starling/display/DisplayObjectContainer.hx line 449    
Called from starling/display/DisplayObject.hx line 778             
Called from a C function                                           
Called from starling/events/EventDispatcher.hx line 144            
Called from starling/events/EventDispatcher.hx line 184            
Called from haxegon/Core.hx line 173                               
Called from haxegon/Core.hx line 252                               
Called from haxegon/Scene.hx line 53                               
Called from haxegon/Scene.hx line 63                               
Called from haxegon/Scene.hx line 64                               
Called from a C function                                           
Called from Main.hx line 22                                        
Uncaught exception - Invalid field access : update                 
```

**Comment by TerryCavanagh** [comment]
Hmm! I'm not sure, but I suspect this line:

`start = Core.time;`

Try moving that into `new()`, and see if that fixes it?

**Comment by marioboi3112** [comment]
still the same error, maybe it could be the way the Classes's method is being called, here is the Main.hx file tho
```haxe
import haxegon.*;

import Player;
import Menu;

class Main {
  private var screen_col = Col.RED; // Use the Col enum to specify the color or use Hex Code for the colors!
  public final WINDOW_WIDTH:Int = 720;
  public final WINDOW_HEIGHT:Int = 490; 
  var player:Player = new Player();
  var menu:Menu = new Menu();
  public function new() {
	  init();
	  update();
  }

  function init() {
    Gfx.resizescreen(0, 0); // Specify the screen size
    Gfx.clearcolor = screen_col;
  }
  function update() {
	  player.update();
	  menu.menuStateHandler();
	  menu.update();
  }
}

```
As you can see the Main class wont work with anything regarding the constructor, it will just call the methods of the class...

**Comment by TerryCavanagh** [comment]
Hmmm, my usual code style is to define classes like that inside the init function, but what you're doing should probably work fine. so I dunno! Happy to take a look at the entire project if you like, maybe I can spot something - you can email me here: https://distractionware.com/email/

**Comment by marioboi3112** [comment]
Ok sir, thanks a lot for your help! should i send the Project via your email?

**Comment by TerryCavanagh** [comment]
yep, go for it!

**Comment by marioboi3112** [comment]
![image](https://github.com/haxegon/haxegon/assets/98112470/79f49e5a-3548-4968-981c-1aa80bbfb77e)
not sure if your email works, should i send it on your discord?

**Comment by TerryCavanagh** [comment]
Hmm, weird - yep, discord works, I'm "terrycavanagh" there.

**Comment by TerryCavanagh** [comment]
Hey! Thanks for sending your code via discord! I had a look, and it seems like the issue is specific to Neko builds - Windows and Flash both worked as expected when I tried making builds.

I haven't tested this, but I would guess that Neko builds are broken completely for all sorts of simple haxegon examples. Neko builds have always been temperamental, and it's not a shock that they've broken since I last looked at Haxegon - I suspect a change in openfl/lime or haxe itself is responsible. 

Sorry! Haxegon isn't being updated or supported anymore, so this isn't something I'm planning to fix! I suggest just using native builds if you can, or if you really want to use Neko, to try rolling back to older versions of the openfl/lime and haxe until you find ones that work!

**Comment by marioboi3112** [comment]
Hey there Terry! if the problem is from Neko itself, would it work if i used HL or html5 builds? if not then i will stick with flash, thanks for the help!

**Comment by TerryCavanagh** [comment]
Hashlink doesn't work with OpenFL, but HTML5 should work fine, yep!

**Comment by marioboi3112** [comment]
Ohh yeahh and haxegon is based on OpenFL makes sense... well I tried HTML5 and everything seems to work, i am planning to release this project when its done for Mobile and Desktop devices, is that possible?

**Comment by TerryCavanagh** [comment]
Desktop should be totally fine, yep. Mobile is *probably* fine, though I can't promise anything - the only mobile haxegon project that I'm aware of is Dicey Dungeons! 

Obviously it's fine to use an abandoned library if you like, but you might find something more modern and supported like https://heaps.io/, https://kha.tech/ or https://haxeflixel.com/ is a better choice!

**Comment by marioboi3112** [comment]
I prefered Haxegon, for its simplicity and being relatively easy for beginners, didnt want to Bloat my programs with unwanted stuff like flixel would support even tho flixel is a very amazing tool, not interested at the moment, but yeah i will play around with Haxegon and come back if theres anything wrong, Thanks for the entire convo! cheers! Edit: also was wondering if trace functions would work on HTML5 builds...
