### ISSUE TITLE
rotation not working?

### ISSUE THREAD

**Issue by marioboi3112** [TerryCavanagh/haxegon#335]
i tried adding a line of code that would rotate the square by 3 degrees every frame but the rectangle seems to be static, problem from haxegon or from mmy code?
```haxe
package;

/**
 * ...
 * @author obi3112
 */
import haxegon.*;
class Main 
{	
		var rotation :Float = 0;
	private function meteorTest() {
		rotation += 3;
		Gfx.rotation(rotation,0,0);
		Gfx.fillbox(50.100,0.0,20,20,Col.RED);
	}
	
	
	private function update() {meteorTest(); }
	
	
}
``` 
here is the code in case you wanna check it out!

**Comment by TerryCavanagh** [comment]
Problem with Haxegon, I guess - rotation/scale etc only applies to sprites!
