### ISSUE TITLE
Zeedonk: Support animation code with new parameter settings

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#37]

**Comment by TerryCavanagh** [comment]
Animation is gone from haxegon, it never really worked well anyway

**Comment by increpare** [comment]
are you sure it didn't work?

**Comment by TerryCavanagh** [comment]
Nah, it's rubbish, it's messy and it doesn't work the way people expect animation systems to work. I was just implementing a thing somebody else wanted without really understanding the problem. The library is simpler and better off without the feature - if someone else really wants it they can write an add on!
