### ISSUE TITLE
alter canvas resolution?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#39]
is it possible to change the canvas resolution? trying to alter the values in project.xml and it seems to result in nothing displaying at all :(

**Comment by increpare** [comment]
oh, gfx.resizescreen is good enough for me (but not perfect, because it's still a bit letterboxed)

**Comment by TerryCavanagh** [comment]
Oh, that might be broken in HTML5 just right now. You can probably hack it to a particular resolution if you like. I'll make sure it's working for launch.
