### ISSUE TITLE
loadsound loads .ogg in browser, should load mp3 i think?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#45]
cf https://en.wikipedia.org/wiki/HTML5_Audio#Supported_browsers_2

**Comment by increpare** [comment]
oh god, it's confusing. i don't know how to get sounds to work in the browser really.  I thought I replaced a lot of the "looking for .ogg" stuff but there's stuff further down in lime. Guess I just have ta go with multiple copies of everything. Hmm.

**Comment by increpare** [comment]
actually i can't even get that working right now. uff.  I'll just embed something in the html file myself.

**Comment by TerryCavanagh** [comment]
Haxegon is going to support .OGGs as default for all non-flash platforms, I think, just to keep things licence free. Might make an MP3 extension later!
