### ISSUE TITLE
text.center not working?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#54]
bad bug report number two, sorry for no proper examples...may need to double check ...

```
Text.display(Text.CENTER,Text.CENTER,"DREAM BORER",Col.WHITE);
```

doesn't display

but 
    Text.display(0,0,"DREAM BORER",Col.WHITE);

does.

**Comment by TerryCavanagh** [comment]
There's a whole new backend since this bug, seems to be fixed, so closing!
