### ISSUE TITLE
top of ^ is cropped in dos font

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#58]
<img width="9" alt="screen shot 2016-07-12 at 00 21 00" src="https://cloud.githubusercontent.com/assets/465632/16750039/9209ff50-47c6-11e6-99ec-8118eefcf1d5.png">

not sure what the correct way to fix it is (but I've hacked my own solution for now by setting the offset of char 94 to 0 :) )

**Comment by TerryCavanagh** [comment]
Fixed!
