### ISSUE TITLE
Fix resizing

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#73]
Resizing should be safe (right now it causes a crash!) and user definable (do we stretch the screen? do we letterbox and keep pixel perfect?)

**Comment by increpare** [comment]
You know my thoughts on this!

**Comment by TerryCavanagh** [comment]
This is haxegon! :D

**Comment by increpare** [comment]
YOU STILL KNOW MY THOUGHTS.

**Comment by increpare** [comment]
(nice to see you getting through so many haxegon issues!)

**Comment by TerryCavanagh** [comment]
User definable resize settings I want:

 - Letterboxing - whatever width and height you specify in the project.xml is your canvas size. Resizing the screen scales it up and down, but keeps it at the same aspect ratio and letterboxes the rest of the window/screen. (Use case: Default behaviour)
- Letterboxing to pixel ratio - As above, but scales to the nearest pixel perfect ratio, leaving a letterbox both to the side and top and bottom of the window. (Use case: Low resolution games where you care about keeping the pixel size correct)
 - Full canvas - Changes the actual screen size to whatever the window size is, changes the values of Gfx.screenwidth and Gfx.screenheight to match. Settings for width and height in project.xml simply specify the default window size. (Use case: games where you care about having a 1 to 1 scale canvas regardless of size)
 - Dynamic canvas - Like letterboxing, create a canvas of a specified width and height, and scale that canvas as you resize the screen/window. Unlike letterboxing, only scale the Y axis - the X axis instead changes size, so you always have a canvas that fills the entire window. (Use case: a game where you want the screen to be 480 pixels high, and want to fill the entire screen width without letterboxing. My current project!)

**Comment by TerryCavanagh** [comment]
Ok, have done a bunch of work to make this better! New features:

``` haxe
Gfx.resizescreen(width, height);
```
This gives you **Letterboxing** behaviour - the screen will be resized to fit the window, and will create black bars on the side to fit.
``` haxe
Gfx.resizescreen(0, 0);
```
This gives you **Full canvas** behaviour. It changes the actual screen size to whatever the window size is, and changes the values of Gfx.screenwidth and Gfx.screenheight to match.

``` haxe
Gfx.resizescreen(200, 0);
Gfx.resizescreen(0, 200);
```
Either of these will give you a **Dynamic canvas** - the number you specify is respected, and the other dimension changes to match - giving you a completely full screen scaled to whatever value you want.

Finally:
``` haxe
Gfx.keeppixelratio = true;
```
When used with a regular letterboxed screen, this enforces pixel perfect scaling, even if doing so creates black boxes on all edges of the screen. (Only useful for super low res stuff probably)
