### ISSUE TITLE
Rethink music and sound

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/haxegon#75]
The distinction that exists between music and sound that in Haxegon could be better. For example, in Haxegon it's currently very difficult to do crossfading, and to have ambient, looping background sounds in addition to music. A restructure might make this work better. How do other libraries do this anyway? Investigate!

**Comment by increpare** [comment]
Flixel sounds have FadeIn  and FadeOut methods, which work pretty well.  If
you want to crossfade, you just call both at once.  (
http://flixel.org/docs/org/flixel/FlxSound.html  )

**Comment by TerryCavanagh** [comment]
```Also, would be super nice to be able to specify a string for stopsound or at least for stopmusic, to specify which thing to stop.```

**Comment by TerryCavanagh** [comment]
gonna pushh this back againnnnn :(
